In [27]:
#imports

import pandas as pd

# Extract

In [28]:
# read csv 
df = pd.read_csv('World_Happiness_Report_2024.csv', sep=',')
df.head()

,Country name,year,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect
0,Afghanistan,2008,3.723590,7.350416,0.450662,50.500000,0.718114,0.164055,0.881686,0.414297,0.258195
1,Afghanistan,2009,4.401778,7.508646,0.552308,50.799999,0.678896,0.187297,0.850035,0.481421,0.237092
2,Afghanistan,2010,4.758381,7.613900,0.539075,51.099998,0.600127,0.117861,0.706766,0.516907,0.275324
3,Afghanistan,2011,3.831719,7.581259,0.521104,51.400002,0.495901,0.160098,0.731109,0.479835,0.267175
4,Afghanistan,2012,3.782938,7.660506,0.520637,51.700001,0.530935,0.234157,0.775620,0.613513,0.267919

# Transform

In [29]:
column_renaming: dict = {
    "Country name": "pais",
    "year": "ano",
    "Life Ladder": "escada_da_vida",
    "Log GDP per capita": "log_pib_per_capita",
    "Social support": "suporte_social",
    "Healthy life expectancy at birth": "expectativa_de_vida_saudavel_ao_nascer",
    "Freedom to make life choices": "liberdade_de_escolhas_de_vida",
    "Generosity": "generosidade",
    "Perceptions of corruption": "perceção_de_corrupcao",
    "Positive affect": "afeto_positivo",
    "Negative affect": "afeto_negativo",
    }

df = df.rename(columns=column_renaming)
df.columns

Index(['pais', 'ano', 'escada_da_vida', 'log_pib_per_capita', 'suporte_social',
       'expectativa_de_vida_saudavel_ao_nascer',
       'liberdade_de_escolhas_de_vida', 'generosidade',
       'perceção_de_corrupcao', 'afeto_positivo', 'afeto_negativo'],
      dtype='str')

In [ ]:
def classify_happiness(score):
    if score > 6.5:
        return 'Alta'
    elif score >= 5.0:
        return 'Média'
    else:
        return 'Baixa'
    
df['felicidade'] = df[
    ['escada_da_vida', 'log_pib_per_capita', 'suporte_social',
       'expectativa_de_vida_saudavel_ao_nascer',
       'liberdade_de_escolhas_de_vida', 'generosidade',
       'perceção_de_corrupcao', 'afeto_positivo', 'afeto_negativo']
    ].median(axis=1)
# or if we only had numeric vlaues to calc the mean:
# df['felicidade'] = df.select_dtypes(include='number').mean(axis=1)

df['nivel_felicidade'] = df['felicidade'].apply(classify_happiness)
df.groupby(['pais', 'nivel_felicidade'])['nivel_felicidade'].count()

pais         nivel_felicidade
Afghanistan  Baixa               15
Albania      Baixa               16
Algeria      Baixa               11
Angola       Baixa                4
Argentina    Baixa               18
                                 ..
Vietnam      Alta                 1
             Baixa               17
Yemen        Baixa               14
Zambia       Baixa               17
Zimbabwe     Baixa               18
Name: nivel_felicidade, Length: 170, dtype: int64

In [ ]:
latin_america = [
    "Argentina",
    "Bolivia",
    "Brazil",
    "Chile",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Dominican Republic",
    "Ecuador",
    "El Salvador",
    "Guatemala",
    "Haiti",
    "Honduras",
    "Mexico",
    "Nicaragua",
    "Panama",
    "Paraguay",
    "Peru",
    "Uruguay",
    "Venezuela",
]

df_latin_america = df[ df['pais'].isin(latin_america) ].sort_values('pais')
df_latin_america

,pais,ano,escada_da_vida,log_pib_per_capita,suporte_social,expectativa_de_vida_saudavel_ao_nascer,liberdade_de_escolhas_de_vida,generosidade,perceção_de_corrupcao,afeto_positivo,afeto_negativo,felicidade,nivel_felicidade
46,Argentina,2006,6.312925,9.936886,0.938463,65.820000,0.733004,-0.162121,0.851799,0.748283,0.328230,0.851799,Baixa
63,Argentina,2023,6.393229,9.993596,0.892118,67.300003,0.831684,-0.129061,0.846094,0.720122,0.301162,0.846094,Baixa
62,Argentina,2022,6.260993,10.018916,0.893330,67.250000,0.825189,-0.130209,0.810037,0.724068,0.284279,0.825189,Baixa
61,Argentina,2021,5.908279,9.977073,0.882305,67.199997,0.819479,-0.014380,0.816257,0.684860,0.345132,0.819479,Baixa
60,Argentina,2020,5.900567,9.887623,0.897104,67.150002,0.823392,-0.130778,0.815780,0.679317,0.342497,0.823392,Baixa
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2279,Venezuela,2006,6.525146,9.467176,0.946310,65.459999,0.798281,-0.037244,0.646171,0.836672,0.178483,0.836672,Baixa
2278,Venezuela,2005,7.169621,9.316229,0.955278,65.500000,0.838198,NaN,0.719800,0.802929,0.233014,0.896738,Baixa
2294,Venezuela,2022,5.948992,NaN,0.899366,63.875000,0.770417,NaN,0.798016,0.754337,0.292252,0.798016,Baixa
2285,Venezuela,2013,6.552796,9.801931,0.896301,65.180000,0.641965,-0.229989,0.837300,0.812144,0.237609,0.837300,Baixa
2295,Venezuela,2023,5.765363,NaN,0.884668,63.700001,0.756530,NaN,0.825393,0.757685,0.300038,0.825393,Baixa

# Load

In [33]:
df_latin_america.to_csv('relatorio_felicidade_latam_2024.csv', index=False)